import type {
  ActivityRecord,
  Approval,
  ConnectionRecord,
  Decision,
  MemoryRecord,
  Project,
} from "./types";

export const seedProjects: Project[] = [
  {
    id: "thc",
    name: "The Hendricks Company",
    objective: "Operate the creator-ownership ecosystem as the master company.",
    state: "Active",
    health: 76,
    nextAction: "Define the next 30-day operating sprint.",
    owner: "Marcus",
    updatedAt: "2026-07-18",
  },
  {
    id: "agora",
    name: "Agora Capital",
    objective: "Build communal capital infrastructure for builders and creators.",
    state: "Active",
    health: 63,
    nextAction: "Resolve the MVP structure and membership offer.",
    owner: "Marcus",
    blocker: "Legal and product sequencing are not yet locked.",
    updatedAt: "2026-07-18",
  },
  {
    id: "renaissance",
    name: "The Renaissance Project",
    objective: "Create a place-based operating system for human development.",
    state: "Waiting",
    health: 58,
    nextAction: "Convert the place vision into a site and program brief.",
    owner: "Marcus",
    updatedAt: "2026-07-15",
  },
  {
    id: "mhm",
    name: "Marcus Hendricks Ministries",
    objective: "Build the nonprofit and faith-based arm of the ecosystem.",
    state: "Waiting",
    health: 45,
    nextAction: "Clarify the first programs and legal relationship to THC.",
    owner: "Marcus",
    updatedAt: "2026-07-12",
  },
  {
    id: "show",
    name: "The Marcus Hendricks Show",
    objective: "Turn Marcus's thinking and conversations into a durable media property.",
    state: "Stalled",
    health: 35,
    nextAction: "Choose one repeatable weekly format and publishing rhythm.",
    owner: "Marcus",
    blocker: "No operating cadence.",
    updatedAt: "2026-07-10",
  },
  {
    id: "ace",
    name: "ACE",
    objective: "Reduce what Marcus must remember, coordinate, and carry alone.",
    state: "Active",
    health: 82,
    nextAction: "Rehabilitate the repository and connect the first real systems.",
    owner: "ACE",
    updatedAt: "2026-07-18",
  },
];

export const seedDecisions: Decision[] = [
  {
    id: "ace-first-integration",
    question: "What should ACE integrate first after the command center?",
    project: "ACE",
    recommendation: "Start with a daily briefing using Gmail and Google Calendar read access.",
    urgency: "Today",
    confidence: 92,
    reversibility: "Easy",
    deadline: "2026-07-19",
    status: "Open",
  },
  {
    id: "agora-membership-first",
    question: "Should Agora launch as a membership product before capital formation?",
    project: "Agora Capital",
    recommendation: "Yes. Validate participation and operations before regulated capital activity.",
    urgency: "This week",
    confidence: 84,
    reversibility: "Moderate",
    deadline: "2026-07-24",
    status: "Open",
  },
  {
    id: "show-format",
    question: "What is the first public media format?",
    project: "The Marcus Hendricks Show",
    recommendation: "A weekly autobiographical strategy conversation anchored in current work.",
    urgency: "This week",
    confidence: 73,
    reversibility: "Easy",
    deadline: "2026-07-25",
    status: "Open",
  },
];

export const seedApprovals: Approval[] = [
  {
    id: "protect-thursday",
    title: "Protect Thursday afternoon for focused work",
    type: "Calendar change",
    rationale: "The week currently has no uninterrupted strategic block.",
    risk: "Low",
    systems: ["Google Calendar"],
    status: "Pending",
  },
  {
    id: "draft-followup",
    title: "Draft follow-up to ecosystem event contacts",
    type: "Email draft",
    rationale: "Several relationships have no defined next step.",
    risk: "Low",
    systems: ["Gmail", "Contacts"],
    status: "Pending",
  },
  {
    id: "agora-memo",
    title: "Create an Agora legal-structure decision memo",
    type: "Document",
    rationale: "The unresolved structure is blocking product and capital decisions.",
    risk: "Medium",
    systems: ["Google Drive"],
    status: "Pending",
  },
];

export const seedMemories: MemoryRecord[] = [
  {
    id: "model-marketing",
    type: "Principle",
    text: "The model is the marketing.",
    source: "Marcus",
    confidence: "High",
    connectedEntities: ["The Hendricks Company"],
    createdAt: "2025-08-01",
  },
  {
    id: "projects-products",
    type: "Principle",
    text: "Launch projects as products.",
    source: "Marcus",
    confidence: "High",
    connectedEntities: ["The Hendricks Company", "Agora Capital"],
    createdAt: "2025-08-01",
  },
  {
    id: "name-owns-it",
    type: "Identity",
    text: "My name's on it so my name owns it; my name owns it so my name's on it.",
    source: "Marcus",
    confidence: "High",
    connectedEntities: ["The Hendricks Company"],
    createdAt: "2025-09-15",
  },
  {
    id: "organic-documentation",
    type: "Operating rule",
    text: "Organic documentation over a performative content calendar.",
    source: "THC strategy",
    confidence: "High",
    connectedEntities: ["The Hendricks Company", "The Marcus Hendricks Show"],
    createdAt: "2025-08-21",
  },
  {
    id: "fund-build-grow",
    type: "Vision",
    text: "Build systems that let communities fund, build, and grow together.",
    source: "Agora Capital",
    confidence: "High",
    connectedEntities: ["Agora Capital"],
    createdAt: "2025-09-01",
  },
];

export const seedActivities: ActivityRecord[] = [
  {
    id: "repo-rehab",
    action: "Repository rehabilitation started",
    detail: "ACE was separated from the old Agora repository assumptions.",
    createdAt: "2026-07-18T08:30:00-05:00",
  },
];

export const seedConnections: ConnectionRecord[] = [
  { id: "calendar", name: "Google Calendar", description: "Schedule, availability, and meeting preparation", status: "Not connected" },
  { id: "gmail", name: "Gmail", description: "Inbox triage, drafts, and follow-up tracking", status: "Not connected" },
  { id: "drive", name: "Google Drive", description: "Documents, structured memory, and source files", status: "Not connected" },
  { id: "contacts", name: "Google Contacts", description: "People and relationship context", status: "Not connected" },
  { id: "finance", name: "Finance", description: "Read-only cash flow and obligation monitoring", status: "Not connected" },
  { id: "signature", name: "E-signature", description: "Contract routing and approved signature workflows", status: "Not connected" },
];
